[project]
name = "dertour"
version = "0.1.0"
authors = [
	{name = "Clemens Wältken", email =  "clemens.waltken@microsoft.com>"}
]
readme = "README.md"
requires-python = ">=3.12"

description = ""
dependencies = [
	"fastapi",
	"uvicorn",
	"gunicorn"
]

[tool.poetry]
package-mode = false